services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
      - .env.prod
    ports:
      - "${PORT}:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    env_file:
      - .env
      - .env.prod
    volumes:
      - mongo_data:/data/db

  dex:
    image: ghcr.io/dexidp/dex:v2.37.0
    container_name: dex
    volumes:
      - ./config/dex:/etc/dex
    ports:
      - "5556:5556"
    depends_on:
      - mongo
    env_file:
      - .env
      - .env.prod
    entrypoint: ["/bin/sh", "-c"]
    command: ["envsubst < /etc/dex/dex.yaml > /etc/dex/dex_final.yaml && dex serve /etc/dex/dex_final.yaml"]

volumes:
  mongo_data: